---
title: "Untitled"
author: "beatriz"
date: "13/11/2020"
output: html_document
---
# Initialization
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = 'D:/master_thesis')
base <- 210 # width of images
quant <- 5
```

```{r libraries, include=FALSE}
library(tidyverse)
library(ggnewscale)
library(cowplot)
library(patchwork)
source('rscript/00_Maps_eng.R')
```

```{r reading files, echo=FALSE, include=FALSE}
acc <- readr::read_csv('results/02_housing_acc_segreg/table/accessibility_distances.csv') %>% 
  dplyr::mutate(threshold = paste0(threshold, 'min'),
                acc = perc) %>% 
  dplyr::filter(threshold=='60min', year == '2017') %>% 
  dplyr::rename(id = origin) %>% 
  dplyr::select(id, acc)

load('results/02_housing_acc_segreg/table/segregation/localSegreg.rda')
segreg <- lSeg %>% 
  dplyr::filter(measure %in% 'G3_G3', bandwd == 1500) %>% 
  dplyr::rename(seg = value) %>% 
  dplyr::select(id, seg)

df_raw <- dplyr::full_join(acc, segreg) %>% 
  dplyr::mutate(acc = ifelse(is.na(acc), 0, acc),
                seg = ifelse(is.na(seg), 0, seg))

# housing 
housing <- sf::read_sf('data/housing/private/private_scs_paper.shp', 
                       crs = crsdegrees, quiet = T) %>% 
  sf::st_intersection(grid) %>% 
  dplyr::rename(id_grid = id.1)%>% 
  dplyr::mutate(period = factor(period,
                                levels = c('Pre - PMCMV', 'Post - PMCMV'),
                                labels = c('Pre-PMCMV', 'Post-PMCMV')),
                class = factor(class, 
                               levels = c('low', 'medium', 'high'),
                               labels = c('low', 'middle', 'high')),
                db = factor(db,
                            levels = c('regular real estate', 'mcmv'),
                            labels = c('regular real estate', 'MCMV')))

# zeis
zeis02 <- sf::st_read('data/shp/zones/zeis_2002_clean.shp', quiet = T) %>% 
  dplyr::mutate(zeis = as.numeric(stringr::str_replace_all(Layer, 'ZEIS\\_|\\_LIMITE','')),
                id = 1:dplyr::n()) %>% 
  dplyr::select(id, zeis) %>% 
  sf::st_transform(prjdegrees) 

zeis02_sf <- zeis02 %>% 
  dplyr::mutate(year = 'PDE 2002')

# scenarios 
acr <- paste0(rep(rep(c('(B','(M'), each = 3),2), 
              rep(c('L','M','H'), 4),
              rep(c('C)','NC)'), each = 6))

scenarios <- readr::read_csv('results/03_zeis/table/scenarios_paper.csv') %>% 
  mutate(uc = if_else(scenario %% 2==1, 'B','M'),
         dua = case_when(scenario %in% c(1,2,7,8) ~'L',
                         scenario %in% c(3,4,9,10) ~ 'M',
                         T ~ 'H'),
         hulc = if_else(scenario < 7, 'C', 'NC'),
         acronym = paste0('(',uc,dua,hulc,')'),
         scenario = case_when(scenario == 3 ~2,
                              scenario == 5 ~3,
                              scenario == 2 ~4,
                              scenario == 4 ~5,
                              scenario == 9 ~8,
                              scenario == 11 ~9,
                              scenario == 8 ~10,
                              scenario == 10 ~11,
                              T ~scenario),
         scenario = factor(paste('scenario', scenario, acronym),
                           levels = paste('scenario', 1:12, acr),
                           labels = paste('scenario', 1:12, acr)),
         class = factor(class,
                        levels = c('low', 'medium', 'high'),
                        labels = c('low', 'middle', 'high')))

# population
pop_micro <- readr::read_csv('data/population/population_micro_grid2.csv')
```


# Figure 4 - bivariate map

```{r creating breaks}
acc_div <- quantile(x = df_raw$acc, probs = seq(0,1,length.out = 3), 
                    names = F, na.rm = T)
seg_div <- quantile(x = df_raw$seg, probs = seq(0,1,length.out = 3), 
                    names = F, na.rm = T)
```

```{r classes}
df <- df_raw %>%
  dplyr::mutate(seg = ifelse(is.na(seg), 0, seg),
                acc = ifelse(is.na(acc), 0, acc),
                range_acc = as.numeric(as.character(cut(acc,
                                                        breaks = acc_div,
                                                        labels = c(1,3),
                                                        include.lowest = T,
                                                        right = F))),
                range_seg = as.numeric(as.character(cut(seg,
                                                        breaks = seg_div,
                                                        labels = c(1,3),
                                                        include.lowest = T,
                                                        right = F))),
                acc_seg = as.numeric(paste0(range_acc, range_seg))) 

# number and percent of cells in each class
summary_cells <- df %>% 
  dplyr::group_by(acc_seg) %>% 
  dplyr::summarise(n = dplyr::n()) %>% 
  dplyr::ungroup() %>% 
  dplyr::mutate(perc = n/sum(n, na.rm=T)) %>% 
  print()
```

```{r preparation for the map}
# * bivariate maps ----

# colors of accessibility and segregation
col_acc <- unname(colBivariate[c(1,3)])
col_segreg <- unname(colBivariate[c(1,7)])

# dissolve 
plot <- df %>% 
  dplyr::filter(!is.na(acc), !is.na(seg)) %>% 
  dplyr::select(-acc, -seg) %>% 
  tidyr::pivot_longer(c(acc_seg,range_seg, range_acc), 
                      names_to = 'plot', 
                      values_to = 'value') %>% 
  dplyr::mutate(plot = factor(plot,
                              levels = c('range_acc', 'range_seg', 'acc_seg'),
                              labels = c('accessibility', 'segregation', 'bivariate'))) %>% 
  dplyr::right_join(grid) %>% 
  sf::st_as_sf() %>% 
  dplyr::group_by(plot, value) %>% 
  dplyr::summarise() %>% 
  dplyr::ungroup() %>% 
  dplyr::filter(!is.na(plot)) %>% 
  dplyr::mutate(value = as.numeric(value))

# accessibility filter
acc_plot <- dplyr::filter(plot, plot == 'accessibility') %>% 
  dplyr::mutate(value = value-.5)

# segregation filter
seg_plot <- dplyr::filter(plot, plot == 'segregation') %>% 
  dplyr::mutate(value = value-.5)

# bivariate filter
bi_plot <- dplyr::filter(plot, plot == 'bivariate')
```

```{r bivariate map}
# maps
p <- ggplot() +
  annotation_custom(ggbasemap, xmin=-Inf, xmax = Inf, ymin = -Inf, ymax = Inf) +
  # accessibility map
  geom_sf(data = acc_plot, aes(fill = value), color = NA) +
  scale_fill_stepsn(name = '% of total jobs',
                    colors = col_acc,
                    values = scales::rescale((1:2)-.5, 
                                             from = c(0,2)),
                    breaks = 0:2,
                    labels = scales::percent(acc_div, accuracy = 1),
                    limits = c(0, 2),
                    expand = F,
                    right = T,
                    guide = guide_colorsteps(order = 2,
                                             even.steps = F,
                                             title.position = "top",
                                             barheight = base/45,
                                             barwidth = base/3,
                                             default.unit = "mm",
                                             ticks.colour = NA,
                                             override.aes = list(shape = NA,
                                                                 linetype = "blank"))) +
  # segregation map
  new_scale_fill() +
  geom_sf(data = seg_plot, aes(fill = value), color = NA) +
  scale_fill_stepsn(name = 'local isolation high class',
                    colors = col_segreg,
                    breaks = 0:2,
                    values = scales::rescale((1:2)-.5, 
                                             from = c(0,2)),
                    labels = scales::scientific(round(seg_div,6), digits = 1),
                    limits = c(0,2),
                    expand = F,
                    right = T,
                    guide = guide_colorsteps(order = 3,
                                             even.steps = F,
                                             title.position = "top",
                                             barheight = base/45,
                                             barwidth = base/3,
                                             default.unit = "mm",
                                             ticks.colour = NA,
                                             override.aes = list(shape = NA,
                                                                 linetype = "blank"))) +
  # bivariate plot
  new_scale_fill() +
  geom_sf(data = bi_plot, aes(fill = as.character(value)), color = NA, show.legend = F) +
  scale_fill_manual(values = colBivariate,
                    guide = guide_legend(order = 3,
                                         nbin = 200,
                                         title.position = "top",
                                         label.position = "bottom",
                                         barheight = base/45,
                                         barwidth = base/3,
                                         default.unit = "mm",
                                         ticks.colour = NA,
                                         override.aes = list(shape = NA,
                                                             linetype = "blank")),
                    aesthetics = "fill") +
  geom_sf(data = massa, fill = colWater, color = colWater, size = line.size/500)  +
  geom_sf(data=rios, color=colWater, size=line.size/250) + 
  geom_sf(data=verde, fill=colGreen, color="transparent") +
  geom_sf(data=trilhos, aes(color = "trilhos"),
          size = line.size/200, show.legend = F) +
  geom_sf(data=muni, fill = 'grey40', color = 'transparent', alpha = 0.25) +
  scale_color_manual(breaks = "trilhos",
                     values = c("trilhos" = "grey40"),
                     guide = guide_legend(title= "", 
                                          order = 1,
                                          title.position = "top")) +
  ggspatial::annotation_scale(location = 'br', 
                              bar_cols = c('grey15', 'grey99'), 
                              line_width = 0.3,
                              line_col = 'grey15',
                              text_col = 'grey15') +
  labs(caption = paste0(bg$caption))+
  facet_grid(.~plot)+
  theme_bw() +
  theme_map_3 +
  coord_lim 

```

```{r legend}
# * legends ----
legend_bi <- df %>% 
  ggplot() +
  geom_rect(aes(xmin = acc_div[1], ymin = seg_div[1], xmax = acc_div[2], ymax = seg_div[2]), fill = colBivariate['11'])+
  geom_rect(aes(xmin = acc_div[2], ymin = seg_div[1], xmax = acc_div[3], ymax = seg_div[2]), fill = colBivariate['31'])+
  geom_rect(aes(xmin = acc_div[1], ymin = seg_div[2], xmax = acc_div[2], ymax = seg_div[3]), fill = colBivariate['13'])+
  geom_rect(aes(xmin = acc_div[2], ymin = seg_div[2], xmax = acc_div[3], ymax = seg_div[3]), fill = colBivariate['33'])+
  geom_point(aes(x=acc, y = seg), color = 'white', alpha = 0.02, size = 0.01) +
  scale_y_continuous(breaks = seg_div, 
                     trans = scales::pseudo_log_trans(10^-8, base=10),
                     labels = scales::scientific(round(seg_div,6), digits = 1)) +
  scale_x_continuous(breaks = acc_div, 
                     trans = scales::pseudo_log_trans(10^-2, base=10),
                     labels = scales::percent(acc_div, accuracy = 1)) +
  coord_flip(expand = F) +
  labs(x = "> accessibility",
       y = "> segregation") +
  theme_chart +
  theme(axis.line = element_blank(),
        plot.background = element_blank(),
        panel.border = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_text(size = font.size*0.08))

```

```{r final map}
size <- dplyr::filter(map_dim, map=='4')
p2 <- ggdraw(p) +
  draw_plot(legend_bi, 
            x = 1-27/size$width, y = 38/size$height, 
            width = 27/size$width, height = 27/size$height, hjust = 1) 

ggsave('latex/scs_zeis/figure/results/map_bivariate2.png', 
       p2, dpi = 500, width = size$width, height = size$height, units = "mm", type='cairo-png')

p2
```

<!-- # Moran's I -->
<!-- ```{r} -->
<!-- cor <- cor(df$acc, df$seg) -->
<!-- ``` -->


<!-- ```{r Morans I} -->
<!-- moran_aux <- df %>% -->
<!--   dplyr::select(id, acc, seg) %>% -->
<!--   dplyr::right_join(grid) %>% -->
<!--   sf::st_as_sf() %>% -->
<!--   dplyr::mutate(seg = ifelse(is.na(seg), 0, seg), -->
<!--                 acc = ifelse(is.na(acc), 0, acc)) -->

<!-- moran <- accSeg:::globalMoran(moran_aux) -->
<!-- # moran_sim <- ecdf(accSeg:::globalMoranSim(moran_aux)) -->
<!-- # moran_sim(moran) -->
<!-- moran -->
<!-- ``` -->
<!-- # Figure 5 - LISA maps -->
<!-- ```{r LISA prep} -->
<!-- # lisa_shp <- accSeg:::LISAmaps(moran_aux) -->
<!-- #  -->
<!-- # rgdal::writeOGR(sf::as_Spatial(lisa_shp), -->
<!-- #  dsn = '../../results/02_housing_acc_segreg/lisa2.shp', layer = 'lisa', -->
<!-- #  driver = 'ESRI Shapefile') -->
<!-- ``` -->

<!-- ```{r} -->
<!-- lisa_shp <- sf::st_read('results/02_housing_acc_segreg/lisa2.shp', quiet=T) %>%  -->
<!--   sf::st_transform(prjdegrees) %>%  -->
<!--   dplyr::rename(agrupamento = patterns, -->
<!--                 `significância` = pvalue) %>%  -->
<!--   dplyr::select(id, agrupamento, `significância`) %>%  -->
<!--   tidyr::pivot_longer(c(agrupamento, `significância`), names_to = 'var', values_to = 'value') %>%  -->
<!--   sf::st_as_sf() %>%  -->
<!--   dplyr::group_by(var, value) %>%  -->
<!--   dplyr::summarise() %>%  -->
<!--   dplyr::ungroup() %>%  -->
<!--   dplyr::filter(!is.na(value)) %>%  -->
<!--   dplyr::mutate(var = ifelse(var == 'agrupamento', 'cluster', 'significance')) -->

<!-- cluster_p <- dplyr::filter(lisa_shp, var == 'cluster') -->
<!-- pvalue_p <- dplyr::filter(lisa_shp, var == 'significance') -->

<!-- p <- lisa_shp %>%  -->
<!--   ggplot() + -->
<!--   annotation_custom(ggbasemap, xmin=-Inf, xmax = Inf, ymin = -Inf, ymax = Inf) + -->
<!--   geom_sf(data = cluster_p, aes(fill = value), color = NA) + -->
<!--   scale_fill_manual(name = 'cluster', -->
<!--                     breaks = c('High - High', -->
<!--                                'High - Low', -->
<!--                                'Not significant', -->
<!--                                'Low - High', -->
<!--                                'Low - Low'), -->
<!--                     values = c('High - High' = colRedBlue(5)[1], -->
<!--                                'High - Low' = colRedBlue(5)[2], -->
<!--                                'Not significant' = colRedBlue(5)[3], -->
<!--                                'Low - High' = colRedBlue(5)[4], -->
<!--                                'Low - Low' = colRedBlue(5)[5]), -->
<!--                     guide = guide_legend(order = 2, -->
<!--                                          nrow = 1, -->
<!--                                          title.position = "top", -->
<!--                                          label.position = "bottom", -->
<!--                                          barheight = base/45, -->
<!--                                          barwidth = base/3, -->
<!--                                          default.unit = "mm", -->
<!--                                          override.aes = list(shape = NA, -->
<!--                                                              linetype = "blank", -->
<!--                                                              fill = colRedBlue(5)))) + -->
<!--   new_scale_fill() + -->
<!--   geom_sf(data = pvalue_p, aes(fill = value), color = NA) + -->
<!--   scale_fill_manual(name = 'significance', -->
<!--                     limits = c('p = 0.001', -->
<!--                                'p = 0.01', -->
<!--                                'p = 0.05', -->
<!--                                'Not significant'), -->
<!--                     values = c('p = 0.001' = colOrange(5)[3], -->
<!--                                'p = 0.01' = colOrange(5)[2], -->
<!--                                'p = 0.05' = colOrange(5)[1], -->
<!--                                'Not significant' = colRedBlue(5)[3]), -->
<!--                     guide = guide_legend(order = 3, -->
<!--                                          nrow = 1, -->
<!--                                          title.position = "top", -->
<!--                                          label.position = "bottom", -->
<!--                                          barheight = base/45, -->
<!--                                          barwidth = base/3, -->
<!--                                          default.unit = "mm", -->
<!--                                          override.aes = list(shape = NA, -->
<!--                                                              linetype = "blank"))) + -->
<!--   geom_sf(data = massa, fill = colWater, color = colWater, size = line.size/500)  + -->
<!--   geom_sf(data=rios, color=colWater, size=line.size/250) +  -->
<!--   geom_sf(data=verde, fill=colGreen, color="transparent") + -->
<!--   geom_sf(data=muni, fill = 'grey40', color = 'transparent', alpha = 0.25) + -->
<!--   geom_sf(data=trilhos, aes(color = "rails"), -->
<!--           size = line.size/200, show.legend = "line") + -->
<!--   labs(caption = bg$caption) + -->
<!--   scale_color_manual(breaks = "rails", -->
<!--                      values = c("rails" = "grey40"), -->
<!--                      guide = guide_legend(title= "",  -->
<!--                                           order = 1, -->
<!--                                           title.position = "top")) + -->
<!--   ggspatial::annotation_scale(location = 'br',  -->
<!--                               bar_cols = c('grey15', 'grey99'),  -->
<!--                               line_width = 0.3, -->
<!--                               line_col = 'grey15', -->
<!--                               text_col = 'grey15') + -->
<!--   facet_grid(~var) + -->
<!--   theme_bw() + -->
<!--   theme_map_2 + -->
<!--   theme(legend.spacing.x = unit(.1,'cm')) + -->
<!--   coord_lim  -->

<!-- size <- dplyr::filter(map_dim, map=='4') -->
<!-- ggsave(paste0('latex/scs_zeis/figure/results/map_lisa_acc_segreg2.png'), -->
<!--        p, dpi = 500, width = size$width, height = size$height, units = "mm", type = 'cairo-png') -->
<!-- p -->
<!-- ``` -->

# Figure 5 - hotspot
```{r}
housing_coord <- housing %>% 
  rowwise() %>% 
  mutate(lng = unlist(geometry)[1],
         lat = unlist(geometry)[2]) %>% 
  ungroup() %>% 
  sf::st_as_sf() %>% 
  sf::st_drop_geometry()

it <- housing_coord %>% 
  group_by(period, class, db) %>% 
  summarise() %>% 
  ungroup() %>% 
  rename(fs = period,
         fx = class,
         d = db)

z <- pmap_df(it, function(fs, fx, d){
  message(fx, " ", fs, " ", d)
  df <- housing_coord %>% 
    filter(class == fx, period == fs, db == d, !is.na(lng))
  
  dt <- data.table::data.table(df)[,list(lat=rep(lat,uh),lng=rep(lng,uh))]
  
  bwd <- 5*10^-2
  n <- 1000
  
  z <- MASS::kde2d(dt$lng, 
                   dt$lat,
                   n = n,
                   h = rep(bwd, n*n),
                   lims = c(-46.826081, -46.365377, 
                            -23.716492, -23.384091))  
  # c(-46.826081, -46.365377, -23.716492, -23.384091)
  
  t <- data.table::as.data.table(z$z)
  
  data.frame(lng = rep(z$x, n),
             lat = rep(z$y, each = n),
             z = data.table::melt(t),
             period = fs,
             class = fx,
             db = d)
})

z <- z %>% 
  mutate(db = factor(db,
                     levels = c('regular real estate', 'mcmv'),
                     labels = c('regular real estate', 'MCMV')),
         period = str_replace(period, ' - ', '-'),
         period = factor(period,
                         levels = c('Pre-PMCMV', 'Post-PMCMV')),
         class = factor(class,
                        levels = c('low', 'medium','high'),
                        labels = c('low', 'middle','high')))
housing_coord <- housing_coord %>% 
  mutate(db = factor(db,
                     levels = c('regular real estate', 'mcmv'),
                     labels = c('regular real estate', 'MCMV')),
         period = str_replace(period, ' - ', '-'),
         period = factor(period,
                         levels = c('Pre-PMCMV', 'Post-PMCMV')),
         class = factor(class,
                        levels = c('low', 'medium','high'),
                        labels = c('low', 'middle','high')))

p <- ggplot() +
  annotation_custom(ggbasemap_short, xmin=-Inf, xmax = Inf, ymin = -Inf, ymax = Inf) +
  geom_sf(data = massa, fill = colWater, color = colWater, size = line.size/500)  +
  geom_sf(data=rios, color=colWater, size=line.size/250) +
  geom_sf(data=verde, fill=colGreen, color='transparent') +
  geom_sf(data=muni, fill = 'grey40', color = 'transparent', alpha = 0.25) +
  geom_sf(data=trilhos, aes(fill = 'trilhos'), color = 'grey40',
          size = line.size/200, show.legend = 'line') +
  scale_fill_manual(breaks = c('trilhos'),
                    values = c('trilhos' = 'grey40'),
                    labels = c('rails'),
                    guide = guide_legend('',
                                         order = 1,
                                         title.position = 'top',
                                         override.aes = list(shape = NA)))+
  new_scale_fill()+
  geom_point(data = filter(housing_coord),
             aes(lng, lat),
             color = "grey30",
             alpha = 0.1,
             size = .2) +
  new_scale_fill()+
  geom_contour_filled(data = filter(z, z.value > 1),
                      aes(lng, 
                          lat,
                          z = z.value,
                          fill = stat(level)), 
                      alpha = 0.8,
                      bins=5,
                      geom="polygon") +
  scale_fill_manual('# of HUs',
                    values = colorRampPalette(colRedBlue(3)[2:3])(quant+1)[2:6],
                    guide = guide_colorsteps(order = 2,
                                             show.limits = T,
                                             title.position = "top",
                                             barheight = base/45,
                                             barwidth = base/3,
                                             default.unit = "mm",
                                             ticks.colour = NA,
                                             override.aes = list(shape = NA,
                                                                 linetype = "blank")))  +
  
  new_scale_fill()+
  labs(caption = paste0('Pre-PMCMV: 2002-2008; Post-PMCMV: 2009-2014\n',
                        bg$caption))  +
  ggspatial::annotation_scale(location = 'br', 
                              bar_cols = c('grey15', 'grey99'), 
                              line_width = 0.3,
                              line_col = 'grey15',
                              text_col = 'grey15') +
  ggh4x::facet_nested(class ~ period + db, switch = 'y') +
  ggplot2::theme_bw()+
  theme_map +
  coord_lim_short

size <- dplyr::filter(map_dim, map=='3_short')
ggsave(paste0('latex/scs_zeis/figure/results/map_heat_housing2.png'), 
       p, dpi = 500, type = 'cairo-png', width = size$width, height = size$height, units = 'mm')

```


# Figure 6 - scatter plot
```{r scatter plot}
hs_df <- housing %>%
  dplyr::left_join(df, by = c('id_grid' = 'id')) %>% 
  sf::st_drop_geometry()

hs_df_total <- hs_df %>% 
  group_by(period, class, db) %>% 
  summarise(tot = sum(uh, na.rm=T)) %>% 
  ungroup() %>% 
  group_by(period) %>% 
  mutate(perc = tot/sum(tot)) %>% 
  print()


p <- hs_df %>% 
  ggplot() +
  geom_point(data=df, aes(acc, seg), alpha = 0.08, color = 'grey90') +
  geom_point(aes(acc, seg, size = uh), color = colRedBlue(3)[3],alpha = 0.15) +
  geom_text(data = hs_df_total,
            aes(0.0025, seg_div[3], 
                label = paste0('HU total: ', format(tot,
                                                    big.mark = ',',
                                                    decimal.mark = '.'))),
            hjust = 1,
            vjust = 0) +
  scale_size(range = c(0,10),
             labels = scales::number_format(big.mark = ',', decimal.mark = '.')) +
  scale_y_continuous(breaks = seg_div, 
                     trans = scales::pseudo_log_trans(10^-08, base=10),
                     labels = scales::scientific(round(seg_div,6), digits = 1)) +
  scale_x_continuous(breaks = acc_div, 
                     labels = scales::percent_format(accuracy = 1),
                     trans = scales::pseudo_log_trans(10^-02, base=10)) +
  guides(size = guide_legend('HU',
                             title.position = 'top',
                             order = 2)) +
  coord_flip(expand = F, xlim = c(0,.8)) +
  labs(y = 'high class isolation', 
       x = 'accessibility (% of total of jobs)',
       caption = 'Pre - PMCMV: 2002-2008; Post - PMCMV: 2009-2014') +
  ggh4x::facet_nested(class~period+db)+
  theme_chart +
  theme(panel.grid.minor.y = element_blank(),
        panel.spacing.x = unit(10,'mm'),
        panel.spacing.y = unit(4,'mm'),
        plot.caption.position = 'plot')

size <- dplyr::filter(map_dim, map=='chart')
ggsave(paste0('latex/scs_zeis/figure/results/scatterplot_housing_acc_seg2.png'),
       plot = p, dpi = 500, width = size$width, height = size$width, units = "mm", type = 'cairo-png')

```

# Figure 7 - barplot for housing location
```{r}
p <- hs_df %>% 
  mutate(cdb = paste0(class,' - ', db),
         cdb = factor(cdb,
                      levels = c('high - regular real estate',
                                 'middle - regular real estate',
                                 'middle - MCMV',
                                 'low - MCMV')),
         acc_seg = factor(acc_seg),
         acc_seg = forcats::fct_rev(acc_seg)) %>% 
  dplyr::group_by(period, cdb, acc_seg) %>% 
  dplyr::summarise(n = sum(uh)) %>% 
  dplyr::ungroup() %>% 
  dplyr::group_by(period, cdb) %>% 
  dplyr::mutate(perc = n/sum(n, na.rm=T)) %>%
  dplyr::ungroup() %>% 
  mutate(color = if_else(acc_seg == '11', 'grey90', 'grey10'),
         period = factor(period,
                         labels = c('Pre-PMCMV', 'Post-PMCMV'))) %>% 
  ggplot(aes(x = perc, 
             y = cdb, 
             fill = acc_seg))+
  geom_bar(stat = 'identity') +
  scale_fill_manual('accessibility - segregation',
                    values = colBivariate,
                    labels = c('High - High',
                               'High - Low',
                               'Low - High',
                               'Low - Low'),
                    guide = guide_legend(order = 1,
                                         nbin = 200,
                                         title.position = "top",
                                         label.position = "bottom",
                                         barheight = base/45,
                                         barwidth = base/3,
                                         default.unit = "mm",
                                         ticks.colour = NA,
                                         reverse = T)) +
  geom_text(aes(label = scales::percent(perc, accuracy = 1, suffix = ''),
                color = color),
            position = position_stack(vjust = 0.5),
            stat = 'identity',
            show.legend = F) +
  scale_color_manual(values = c('grey90','grey10'))+
  scale_x_continuous(labels = scales::percent, breaks = seq(0,1,.2))+
  labs(x='',y='')+
  coord_cartesian(expand=F)+
  facet_grid(.~period)+
  theme_chart +
  theme(plot.margin = margin(2,7.5,2,2,'mm'))

size <- dplyr::filter(map_dim, map=='chart')
ggsave('latex/scs_zeis/figure/results/barplot_housing_location.png', 
       p, dpi = 500, width = size$width, height = size$height, 
       units = "mm", type = 'cairo-png')
p

```

```{r numeric analysis for housing location}

summary_mcmv <- hs_df %>% 
  dplyr::group_by(period, class,acc_seg) %>% 
  dplyr::summarise(n = sum(uh)) %>% 
  dplyr::ungroup() %>% 
  dplyr::group_by(period, class) %>% 
  dplyr::mutate(perc = n/sum(n, na.rm=T)) %>% 
  filter(perc == max(perc)) %>% 
  print()


summary_mcmv <- hs_df %>% 
  dplyr::group_by(class, range_acc) %>% 
  dplyr::summarise(n = sum(uh)) %>% 
  dplyr::ungroup() %>% 
  dplyr::group_by(class) %>% 
  dplyr::mutate(perc = n/sum(n, na.rm=T)) %>% 
  filter(perc == max(perc)) %>%
  print()


summary_mcmv <- hs_df %>% 
  dplyr::group_by(class, range_seg) %>% 
  dplyr::summarise(n = sum(uh)) %>% 
  dplyr::ungroup() %>% 
  dplyr::group_by(class) %>% 
  dplyr::mutate(perc = n/sum(n, na.rm=T)) %>% 
  filter(perc == max(perc)) %>%
  print()
```
# ZEIS 
```{r preparation of zeis}
zeis <- zeis02 %>%
  dplyr::filter(zeis!=1) %>%
  sf::st_intersection(grid) %>%
  dplyr::rename(id_grid = id.1) %>%
  dplyr::left_join(df, by = c('id_grid' = 'id'))

zeis$area <- sf::st_area(sf::st_transform(zeis, crs = crsutm))

zeis <- zeis %>% 
  dplyr::group_by(id, zeis, acc_seg) %>%
  summarise(area = sum(area,na.rm=T)) %>% 
  ungroup() %>% 
  group_by(id, zeis) %>% 
  filter(area == max(area)) %>% 
  select(-area) %>%
  sf::st_intersection(grid) %>%
  dplyr::rename(id_grid = id.1) %>%
  dplyr::left_join(df, by = c('id_grid' = 'id'))

zeis$area <- sf::st_area(sf::st_transform(zeis, crs = crsutm))

zeis <- zeis %>% 
  group_by(id, zeis, acc_seg.x) %>% 
  summarise(area = sum(area))

int_housing <- sf::st_intersection(housing, zeis) %>% 
  dplyr::rename(id_zeis = id.1) 

out_housing <- housing %>% 
  dplyr::filter(!(id %in% int_housing$id))


zeis <- sf::st_drop_geometry(zeis)
zeis$used <- 0
zeis[zeis$id %in% int_housing$id_zeis, 'used'] <- 1

zeis <- zeis %>% 
  dplyr::mutate(used = ifelse(used== 1, 'used', 'not used'),
                acc_seg = factor(acc_seg.x,
                                 levels = c(11, 13, 31, 33)),
                acc_seg = forcats::fct_rev(acc_seg),
                area = units::drop_units(area),
                zeis = paste('zeis', zeis)) %>% 
  select(-acc_seg.x)

```
## Figure 8 - barplot location of ZEIS

```{r}

zeis_tot <- zeis %>% 
  mutate(zeis = factor(zeis,
                       levels = c('zeis 4', 'zeis 3', 'zeis 2'),
                       labels = c('ZEIS 4', 'ZEIS 3', 'ZEIS 2'))) %>% 
  dplyr::group_by(zeis, acc_seg) %>% 
  dplyr::summarise(n = sum(area)) %>% 
  dplyr::ungroup() %>% 
  dplyr::group_by(zeis) %>% 
  dplyr::mutate(perc = n/sum(n, na.rm=T),
                used = '',
                fac = 'total') %>%
  dplyr::ungroup()

p <- zeis_tot %>% 
  mutate(color = if_else(acc_seg == '11', 'grey90','grey10')) %>% 
  ggplot(aes(x = perc, 
             y = zeis, 
             fill = acc_seg))+
  geom_bar(data = zeis_tot,
           stat = 'identity') +
  scale_fill_manual('accessibility - segregation',
                    values = colBivariate,
                    labels = c('High - High',
                               'High - Low',
                               'Low - High',
                               'Low - Low'),
                    guide = guide_legend(order = 1,
                                         nbin = 200,
                                         title.position = "top",
                                         label.position = "bottom",
                                         barheight = base/45,
                                         barwidth = base/3,
                                         default.unit = "mm",
                                         ticks.colour = NA,
                                         reverse = T)) +
  geom_text(aes(label = scales::percent(perc, accuracy = 1, suffix = ''),
                color = color),
            position = position_stack(vjust = 0.5),
            stat = 'identity',
            show.legend = F) +
  scale_color_manual(values = c('grey90','grey10'))+
  scale_x_continuous(labels = scales::percent, breaks = seq(0,1,.2))+
  labs(x='',y='')+
  coord_cartesian(expand=F)+
  theme_chart +
  theme(plot.margin = margin(2,57.5,2,52,'mm'))

size <- dplyr::filter(map_dim, map=='chart')
ggsave('latex/scs_zeis/figure/results/barplot_zeis_location.png', 
       p, dpi = 500, width = size$width, height = size$height, 
       units = "mm", type = 'cairo-png')

p
```
## numeric analysis:  how many zeis are used?
```{r zeis analysis}
# how many were used?
zeis %>% 
  dplyr::group_by(used) %>% 
  dplyr::summarise(n = dplyr::n(),
                   area = sum(area)) %>% 
  dplyr::ungroup() %>% 
  dplyr::mutate(n = n/sum(n),
                area = area/sum(area)) %>% 
  print()

# and by zeis type
zeis %>% 
  dplyr::group_by(zeis, used) %>% 
  dplyr::summarise(n = dplyr::n(),
                   area = sum(area, na.rm = T)) %>% 
  dplyr::ungroup() %>% 
  dplyr::group_by(zeis) %>% 
  dplyr::mutate(pn = n/sum(n),
                parea = area/sum(area)) %>% 
  print()

# the use of them in general
int_housing %>% 
  sf::st_drop_geometry() %>% 
  dplyr::group_by(zeis) %>% 
  dplyr::summarise(n = dplyr::n()) %>% 
  print()

# the use by class
int_housing %>% 
  sf::st_drop_geometry() %>% 
  dplyr::group_by(zeis, class) %>% 
  dplyr::summarise(n = dplyr::n(),
                   uh = sum(uh)) %>% 
  dplyr::ungroup() %>% 
  dplyr::group_by(zeis) %>% 
  dplyr::mutate(pn = n/sum(n),
                puh = uh/sum(uh)) %>% 
  print()
```
# SCENARIOS

## uh by zeis and scenarios ----
```{r}
ptot <- scenarios %>% 
  dplyr::group_by(scenario, zeis, class) %>% 
  dplyr::summarise(uh = sum(uh)) %>% 
  dplyr::ungroup() %>% 
  dplyr::group_by(scenario, class) %>% 
  dplyr::mutate(puh = uh/sum(uh)) %>% 
  dplyr::ungroup() %>% 
  dplyr::mutate(zeis = ifelse(is.na(zeis), 0, zeis),
                zeis = factor(zeis,
                              levels = c(0, 2, 3))) %>% 
  dplyr::select(-uh) %>% 
  tidyr::pivot_wider(names_from = 'class', values_from = 'puh') %>% 
  dplyr::select(scenario, zeis, low, middle, high) %>% 
  print(., n=66) %>% 
  tidyr::pivot_longer(cols = c('high', 'middle', 'low'), 
                      names_to = 'class', values_to = 'puh') %>% 
  dplyr::filter(!is.na(puh))%>% 
  dplyr::group_by(scenario, class) %>% 
  dplyr::arrange(desc(zeis)) %>% 
  dplyr::mutate(pos = cumsum(puh)-0.05) %>% 
  dplyr::ungroup() %>% 
  dplyr::mutate(class = factor(class,
                               levels = c('low', 'middle', 'high'),
                               labels = c('low', 'middle', 'high'))) 

ptot[7, 'pos'] <- ptot[7, 'pos']+.1
ptot[10, 'pos'] <- ptot[10, 'pos']+.1
ptot[19, 'pos'] <- ptot[19, 'pos']+.1
ptot[31, 'pos'] <- ptot[31, 'pos']+.18
ptot[34, 'pos'] <- ptot[34, 'pos']+.1

tot <- scenarios %>%  
  dplyr::group_by(scenario, class) %>% 
  dplyr::summarise(uh = sum(uh)) %>% 
  dplyr::ungroup() %>% 
  tidyr::pivot_wider(names_from = 'class', values_from = 'uh') %>% 
  print(., n=36) %>% 
  tidyr::pivot_longer(cols = c('high', 'middle', 'low'), 
                      names_to = 'class', values_to = 'uh') %>% 
  dplyr::mutate(class = factor(class,
                               levels = c('low', 'middle', 'high'),
                               labels = c('low', 'middle', 'high')))
```


## Figure 9 - barplot % of relocation
```{r}
p <- scenarios %>% 
  dplyr::group_by(scenario, zeis, class) %>% 
  dplyr::summarise(uh = sum(uh)) %>% 
  dplyr::ungroup() %>% 
  dplyr::mutate(zeis = ifelse(is.na(zeis), 0, zeis),
                zeis = factor(zeis,
                              levels = c(0, 2, 3)),
                names_to = 'class', values_to = 'uh') %>%
  ggplot() +
  geom_bar(aes(x = class, y = uh, fill = zeis), 
           stat = 'identity', position = position_fill()) +
  geom_text(data = tot, aes(x = class, 1.05, 
                            label = format(uh, digits=4,big.mark=',')),
            size = font.size*0.03, color = 'grey10') +
  geom_text(data = ptot, aes(x = class, pos, 
                             label = scales::percent(puh, accuracy = 1)),
            size = font.size*0.03, color = 'grey90') +
  scale_fill_manual('ZEIS',
                    values = c(colRedBlue(2)[2], colOrange(5)[2:3]),
                    breaks = c(0, 2, 3),
                    labels = c('not relocated', '2', '3')) +
  scale_y_continuous(labels = scales::percent) +
  labs(x = '', y = '% of HUs') +
  facet_wrap(.~scenario, ncol=3) +
  theme_chart

size <- dplyr::filter(map_dim, map=='chart')
ggsave(paste0('latex/scs_zeis/figure/results/barplot_relocation.png'),
       p, dpi = 500, width = size$width, height = size$width*1.2, units = "mm")

p
```

## Figure 10 - Gini indexes 
```{r}
base_sc <- housing %>% 
  sf::st_drop_geometry() %>% 
  dplyr::mutate(scenario = 'baseline scenario') %>% 
  dplyr::left_join(acc, by = c('id_grid' = 'id')) %>% 
  dplyr::select(scenario, class, uh, acc)

df <- scenarios %>% 
  dplyr::mutate(scenario = paste('scenario', scenario)) %>% 
  dplyr::filter(uh > 0) %>% 
  dplyr::select(scenario, class, uh, acc) %>% 
  dplyr::bind_rows(base_sc) 

pop <- merge(pop_micro, 
             data.frame(scenario = c(paste('scenario', 1:12, acr), 
                                     'baseline scenario', 
                                     'without propositions'))) %>% 
  dplyr::rename(id = id_grid) %>% 
  tidyr::pivot_longer(g1:g3, 'group', values_to = 'uh') %>% 
  dplyr::mutate(class = 'families') %>% 
  dplyr::left_join(acc)

df_lor <- scenarios %>% 
  dplyr::bind_rows(base_sc) %>% 
  dplyr::mutate(group = dplyr::case_when(class == 'low' ~ 'g1',
                                         class == 'middle' ~ 'g2',
                                         TRUE ~ 'g3'),
                class = 'UH') %>% 
  dplyr::select(-zeis) %>% 
  dplyr::bind_rows(pop) %>% 
  dplyr::mutate(scenario = factor(scenario,
                                  levels = c('without propositions',
                                             'baseline scenario', 
                                             paste('scenario', 1:12, acr)))) %>% 
  dplyr::filter(!is.na(acc), !is.na(uh)) %>% 
  dplyr::group_by(scenario) %>% 
  dplyr::arrange(acc) %>% 
  dplyr::mutate(cumuh = cumsum(uh)/sum(uh, na.rm = T),
                cumacc = cumsum(acc*uh)/sum(acc*uh, na.rm = T)) %>% 
  dplyr::ungroup()
```



```{r}
# figure 11: gini of municipality ----

gini <- df_lor %>%  
  dplyr::group_by(scenario) %>% 
  dplyr::arrange(acc) %>% 
  dplyr::mutate(gini1 = (dplyr::lead(cumuh)-cumuh)*(dplyr::lead(cumacc)+cumacc)) %>% 
  dplyr::filter(!is.na(gini1)) %>% 
  dplyr::summarise(gini = 1 - sum(gini1)) 


gini_org <- gini %>% 
  dplyr::filter(scenario == 'without propositions') %>% 
  .$gini

gini %>% 
  dplyr::filter(scenario != 'without propositions') %>% 
  dplyr::select(scenario, gini) %>%
  dplyr::mutate(scenario = str_replace(scenario, 'scenario',''),
                scenario = str_trim(scenario),
                scenario = factor(scenario,
                                  levels = c('baseline',
                                             paste(1:12, acr)))) %>% 
  ggplot(aes(x = scenario, y = gini)) +
  geom_hline(aes(yintercept = gini_org), color="grey50", 
             lwd = line.size*.006, lty = 'dashed') +
  geom_segment(aes(x = scenario, xend = scenario, y=gini_org, yend = gini)) +
  geom_point(color = colRedBlue(3)[3], size = 4) +
  geom_text(aes(label = format(gini, digits = 4, decimal.mark = '.')), 
            nudge_x = .35,
            nudge_y = -.002)+
  geom_text(x = 12.7, y = gini_org+.001, 
            label = paste('original: ', 
                          format(gini_org, digits = 4, decimal.mark = ','))) +
  coord_cartesian(ylim=c(0.48, 0.52), xlim = c(0.25,13.75), expand = F)+
  labs(x = 'scenario', y='Gini') +
  theme_chart +
  theme(axis.line.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_text(angle=30, hjust = 1))

size <- dplyr::filter(map_dim, map=='chart')
ggsave("latex/scs_zeis/figure/results/gini_scenarios_pop.png", 
       dpi = 500, width = size$width, height = size$height, units = "mm")
```

## Figure 11 - Lorenz curves

```{r}
# figure 12: lorenz scenarios ----

df_lor <- df_lor %>%
  dplyr::mutate(scenario = factor(scenario,
                                  levels = c('without propositions',
                                             'baseline scenario', '', 
                                             paste('scenario', 1:6, acr[1:6])))) %>% 
  dplyr::filter(!is.na(scenario))


median_uh <- df_lor %>% 
  dplyr::filter(group!='', class != 'families') %>% 
  dplyr::group_by(group, class, scenario) %>% 
  dplyr::summarise(median.x = matrixStats::weightedMedian(cumuh, uh),
                   median.y = matrixStats::weightedMedian(cumacc, uh)) %>% 
  dplyr::ungroup()

median <- df_lor %>% 
  dplyr::filter(group!='') %>% 
  dplyr::group_by(group, scenario) %>% 
  dplyr::summarise(median.x = matrixStats::weightedMedian(cumuh, uh),
                   median.y = matrixStats::weightedMedian(cumacc, uh)) %>% 
  dplyr::ungroup() %>% 
  dplyr::mutate(class = 'all') %>% 
  dplyr::bind_rows(median_uh)

gini <- gini %>%
  dplyr::mutate(scenario = factor(scenario,
                                  levels = c('without propositions',
                                             'baseline scenario', '', 
                                             paste('scenario', 1:6, acr[1:6])))) %>% 
  dplyr::filter(!is.na(scenario))

p <- df_lor %>% 
  ggplot() +
  geom_line(aes(x=cumuh, y=cumacc), 
            lwd = line.size*.008)+
  # abline
  geom_abline(intercept=0, slope=1, color="grey50", 
              lwd = line.size*.006, lty = 'dashed') +
  # all points
  geom_point(data = median,
             aes(x = median.x, y = median.y, 
                 color = group, shape = class), size = 3) +
  # UH points
  geom_point(data = median_uh,
             aes(x = median.x, y = median.y, 
                 color = group, shape = class), size = 3) +
  # gini
  geom_text(data = gini,
            aes(x = 0.25, y = 0.95,
                label = paste0('Gini: ', format(gini,digits=4,decimal.mark='.')))) +
  scale_color_manual('group',
                     breaks = paste0('g',1:3),
                     labels = paste0('G',1:3),
                     values = colOrange(5)[c(1,3,5)]) +
  scale_shape_manual('family',
                     breaks = c('all', 'UH'),
                     labels = c('all + HU', 'proposed HU'),
                     values = 16:17)+
  scale_x_continuous(labels = scales::percent) +
  scale_y_continuous(labels = scales::percent) +
  labs(x='family', y='accessibility',
       caption = 'G1: family income up to 3MW, G2: family income between 3MW and 10MW, G3: family income above 10MW') + 
  coord_fixed(xlim=c(0,1), ylim=c(0,1), expand = F)+ 
  facet_wrap(~ scenario, drop = F)+
  theme_chart +
  theme(panel.spacing = unit(7.5, 'mm'),
        plot.caption.position = 'plot',
        legend.position = c(0.85,0.85))
p

g <- ggplotGrob(p)
# get the grobs that must be removed
rm_grobs <- g$layout$name %in% c("panel-1-3", "strip-t-3-1")
# remove grobs
g$grobs[rm_grobs] <- NULL
g$layout <- g$layout[!rm_grobs, ]

size <- dplyr::filter(map_dim, map=='chart')
ggsave("latex/scs_zeis/figure/results/lorenz_scenarios_pop.png", 
       g, dpi = 500, width = size$width, height = size$width, units = "mm")
```

